name: Build and deploy Node.js app to Azure Web App - FronteEnd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present

      - name: Archive production build
        id: archive-production
        run: |
          zip -r production.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: production.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FronteEnd'
          slot-name: 'Production'
          package: ${{ github.workspace }}/production.zip
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Set up Node.js for integration tests
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Run integration tests
        run: |
          # Add your integration test commands here

      - name: Logout of Azure
        run: az logout
